Feature/block validators chart page
GeoDB-Limited/odin-blockchain-scan pull request #16
Opened 2021-09-28 13:46 UTC by Intent-five-dev

2021-09-29 09:33 UTC, invisiburu requested changes

2021-09-29 09:33 UTC, invisiburu commented on src/components/InfoPanel/InfoPanel.vue
> +    })
Лучше выдели новую компоненту с осмысленным названием. Например, если это бублик, то сделай DonutChart.

2021-09-29 09:33 UTC, invisiburu commented on src/helpers/helpers.ts
> +    colors.push(`#${Math.floor(Math.random() * 16777215).toString(16)}`)
мне кажется, что цвета должны быть персистентными

2021-09-29 09:33 UTC, invisiburu commented on src/views/validatorsChart.vue
> +      // },
это не готово?

2021-09-29 09:36 UTC, Intent-five-dev commented on src/views/validatorsChart.vue
> +      // },
Это нереализованный переисбыток, и удалять не хотелось, потому что может найду решение лучше чем hoverBorderWidth: 6

2021-09-29 09:37 UTC, invisiburu commented
И вообще, у тебя есть AppChart, есть Chart, а есть ValidatorsChart. Последний помимо графика еще и кучу не относящейся к графику инфы содержит. А первые два не понятно чем отличаются. Удали лишние, разбей на компоненты и дай нормальные названия чтобы не путать. Может AppChart и Char просто стилизуются по разному?

2021-09-30 10:36 UTC, invisiburu requested changes

2021-09-30 10:36 UTC, invisiburu commented on src/helpers/helpers.ts
> +export const getRandomColors = cacheAnswers(_randomColors)
что это за ужас? мы же не об этом договаривались

2021-10-04 12:17 UTC, merged